spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/init-db.sql

logging:
  level:
    org.springframework.web: DEBUG