spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:db/init-db.sql
      mode: always

logging:
  level:
    org.springframework.web: DEBUG